# Site
name: 'Tigillo Tech Startup Consultancy'
shortname: 'tigillo'
companyname: 'Tigillo Consultancy Ltd'
description: 'We are a UK based tech starup consultancy providing software development services for Tech Startups and Tech Scaleups worldwide. As a Tech Startup Consulting company we connect technology and domain, helping tech startups to build their core software technology and with the production record DevOps Consulting experience, we help our clients to scale with flexibility on the cloud environments and create seamless application development experience.'
url: "https://tigillo.com"
logo: 'assets/images/tigillo-tech-startup-consultancy-logo.svg'
favicon: 'assets/images/tigillo-tech-startup-consultancy-favicon.png'
disqus: 'tigillo'
email: 'contact@tigillo.com'

include: ["_pages"]
permalink: /:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
