# Site
name: 'Tigillo UK'
shortname: 'tigillo'
companyname: 'Tigillo Consultancy Ltd'
description: 'We are a UK based software development company serving Tech Startups and Enterprises worldwide. We connect technology and domain, helping our clients to build their core software technology. We help our clients to scale their software with flexibility on the cloud environments and create seamless application development experience.'
url: "https://tigillo.com"
logo: 'assets/images/tigillo-tech-startup-consultancy-logo.svg'
favicon: 'assets/images/tigillo-tech-startup-consultancy-favicon.png'
disqus: 'tigillo'
email: 'contact@tigillo.com'

include: ["_pages","_services"]
permalink: /:categories/:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      active: insights

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

  # all services
  - scope:
      path: "_services"
    values:
      layout: intro
      social: hide
      active: services
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 20


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
